name: travel_guide_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: fonts/Nunito-Black.ttf
          weight: 900
        - asset: fonts/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: fonts/Nunito-Medium.ttf
          weight: 500
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito-Italic.ttf
          style: italic
        - asset: fonts/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Nunito-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic

    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
